version: "3"
services:
  srv_pg:
    container_name: srv_pg
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      pg_network:

  srv_pgadmin:
    container_name: srv_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    networks:
      pg_network:

networks:
  pg_network:
    driver: bridge