name: CI
on: [pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Format
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --watchAll --coverage
      - name: Build
        run: yarn build
